--- 
user: centos
group: centos
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: staging
max_persistent_conns: 512
servers: 1
daemonize: true
chdir: /home/centos/vhosts/yarvis.staging/current
address: 0.0.0.0
port: 8081
